version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install AWS-Cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt-get update -y
            sudo apt-get install -y less   
      - setup_remote_docker:
          version: 19.03.13       
      - run:
          name: Docker Push
          command: |
            ls -al
            cd back-end/
            docker login -u $DNAME -p $DPASS
            docker build -t vkrutarth/uber-be .
            docker push vkrutarth/uber-be:circleci .  