version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Install AWS-Cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt-get update -y
            sudo apt-get install -y less   
      - run:
          name: Install KubeCtl
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            kubectl version --short --client
      - run:
          name: Install AWS-Auth
          command: |
            cd ~
            curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - setup_remote_docker:
          version: 19.03.13 
      - run:
          name: Docker Image Push Back-End
          command: |
            ls -al
            cd back-end/
            docker login -u $DNAME -p $DPASS
            docker build -t vkrutarth/uber-be:latest .
            docker push vkrutarth/uber-be:latest
            sleep 10
      - run:
          name: Configuring Kubectl
          command: |
            aws eks update-kubeconfig --name terraform-eks-demo-kmv --region us-east-1 --role-arn arn:aws:iam::254747811220:user/circle-ci
            cp config ~/.kube/config
            kubectl apply -f config-map-aws-auth.yml
            sleep 10
            kubectl get nodes      
      - run:
          name: Deploying Back-end Pods
          command: |
            cd back-end/
            kubectl apply -f be-uber-deployment.yaml
            sleep 10
            kubectl get deployments
            kubectl apply -f be-uber-service.yaml
            sleep 10
            kubectl get svc
            sleep 20
      - run:
          name: Docker Image Push Front-End
          command: |
            ls -al
            cd front-end/
            CI=true npm test
            docker login -u $DNAME -p $DPASS
            REACT_APP_URL=http://`kubectl get service/be-uber -o jsonpath={.status.loadBalancer.ingress..hostname}`
            docker build --build-arg REACT_APP_URL=$REACT_APP_URL -t vkrutarth/uber-fe:latest .
            docker push vkrutarth/uber-fe:latest
            sleep 10
      - run:
          name: Deploying Front-end Pods
          command: |
            cd front-end/
            kubectl apply -f fe-uber-deployment.yaml
            sleep 10
            kubectl get deployments
            kubectl apply -f fe-uber-service.yaml
            sleep 10
            kubectl get svc